// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkX1-EbvNYm7HTgrRjlOZkKBEYmqPXLl4',
    appId: '1:578746385191:web:94df9ae833630a4c791f02',
    messagingSenderId: '578746385191',
    projectId: 'procureflow-faysal',
    authDomain: 'procureflow-faysal.firebaseapp.com',
    storageBucket: 'procureflow-faysal.firebasestorage.app',
    measurementId: 'G-01HGXHXD4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmyntaOrytZ9bPxLxQfMrd_lPd-0GtjE',
    appId: '1:578746385191:android:608ff2503bf905b8791f02',
    messagingSenderId: '578746385191',
    projectId: 'procureflow-faysal',
    storageBucket: 'procureflow-faysal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfbJABimJZIbzZ4n4aTebiw7enOILPK4',
    appId: '1:578746385191:ios:296f5e2e2867021b791f02',
    messagingSenderId: '578746385191',
    projectId: 'procureflow-faysal',
    storageBucket: 'procureflow-faysal.firebasestorage.app',
    iosBundleId: 'com.procurementfaysal.bd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChfbJABimJZIbzZ4n4aTebiw7enOILPK4',
    appId: '1:578746385191:ios:c1cf62a69dc865ee791f02',
    messagingSenderId: '578746385191',
    projectId: 'procureflow-faysal',
    storageBucket: 'procureflow-faysal.firebasestorage.app',
    iosBundleId: 'com.example.procurementManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkX1-EbvNYm7HTgrRjlOZkKBEYmqPXLl4',
    appId: '1:578746385191:web:0a059adacedf6928791f02',
    messagingSenderId: '578746385191',
    projectId: 'procureflow-faysal',
    authDomain: 'procureflow-faysal.firebaseapp.com',
    storageBucket: 'procureflow-faysal.firebasestorage.app',
    measurementId: 'G-KCQ0V8N8MH',
  );
}
